Update baseUrl and paths in tsconfig.json (#125)
With updates to start using `tsgo` we are seeing the following class of
errors:

```tsconfig.json:24:5 - error TS5102: Option 'baseUrl' has been removed. Please remove it from your configuration.
  Use '"paths": {"*": "./*"}' instead.

24     "baseUrl": ".",
       ~~~~~~~~~
tsconfig.json:27:9 - error TS5090: Non-relative paths are not allowed. Did you forget a leading './'?

27         "src/*"
           ~~~~~~~

Found 2 errors in the same file, starting at: tsconfig.json:24```

https://www.typescriptlang.org/tsconfig/#baseUrl
> As of TypeScript 4.1, baseUrl is no longer required to be set when using paths.

---------

Co-authored-by: Jason R. Clark <jasonrclark@github.com>